// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// c_D_cross_2d_box
List c_D_cross_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector types, NumericVector intensities, NumericVector r);
RcppExport SEXP _Kcross_c_D_cross_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP typesSEXP, SEXP intensitiesSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(c_D_cross_2d_box(x, bbox, types, intensities, r));
    return rcpp_result_gen;
END_RCPP
}
// c_K_cross_2d_box
List c_K_cross_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector types, int ntypes, NumericVector r, int correction);
RcppExport SEXP _Kcross_c_K_cross_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP typesSEXP, SEXP ntypesSEXP, SEXP rSEXP, SEXP correctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< int >::type ntypes(ntypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    rcpp_result_gen = Rcpp::wrap(c_K_cross_2d_box(x, bbox, types, ntypes, r, correction));
    return rcpp_result_gen;
END_RCPP
}
// c_K_2d_box
NumericVector c_K_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector r, int correction);
RcppExport SEXP _Kcross_c_K_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP rSEXP, SEXP correctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    rcpp_result_gen = Rcpp::wrap(c_K_2d_box(x, bbox, r, correction));
    return rcpp_result_gen;
END_RCPP
}
// c_K_cross_2d_box_just_one_from
List c_K_cross_2d_box_just_one_from(NumericMatrix x, NumericMatrix bbox, NumericVector types, int from, int ntypes, NumericVector r, int correction);
RcppExport SEXP _Kcross_c_K_cross_2d_box_just_one_from(SEXP xSEXP, SEXP bboxSEXP, SEXP typesSEXP, SEXP fromSEXP, SEXP ntypesSEXP, SEXP rSEXP, SEXP correctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type ntypes(ntypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    rcpp_result_gen = Rcpp::wrap(c_K_cross_2d_box_just_one_from(x, bbox, types, from, ntypes, r, correction));
    return rcpp_result_gen;
END_RCPP
}
// c_K_cross_partial_box
NumericMatrix c_K_cross_partial_box(NumericMatrix x, IntegerVector types, int ntypes, NumericVector counts, NumericVector intensities, NumericMatrix bbox, NumericVector r);
RcppExport SEXP _Kcross_c_K_cross_partial_box(SEXP xSEXP, SEXP typesSEXP, SEXP ntypesSEXP, SEXP countsSEXP, SEXP intensitiesSEXP, SEXP bboxSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< int >::type ntypes(ntypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(c_K_cross_partial_box(x, types, ntypes, counts, intensities, bbox, r));
    return rcpp_result_gen;
END_RCPP
}
// c_K_partial_box
NumericMatrix c_K_partial_box(NumericMatrix x, NumericMatrix bbox, NumericVector r);
RcppExport SEXP _Kcross_c_K_partial_box(SEXP xSEXP, SEXP bboxSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(c_K_partial_box(x, bbox, r));
    return rcpp_result_gen;
END_RCPP
}
// c_bbox_disc_intersection
NumericMatrix c_bbox_disc_intersection(NumericMatrix x, NumericMatrix bbox, double r);
RcppExport SEXP _Kcross_c_bbox_disc_intersection(SEXP xSEXP, SEXP bboxSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(c_bbox_disc_intersection(x, bbox, r));
    return rcpp_result_gen;
END_RCPP
}
// c_guan_doublesum_2d_box
NumericVector c_guan_doublesum_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector bw);
RcppExport SEXP _Kcross_c_guan_doublesum_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(c_guan_doublesum_2d_box(x, bbox, bw));
    return rcpp_result_gen;
END_RCPP
}
// c_iD_cross_2d_box
List c_iD_cross_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector types, int ntypes, NumericVector intensities, NumericVector min_intensities, NumericVector bdist, NumericVector r, int correction);
RcppExport SEXP _Kcross_c_iD_cross_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP typesSEXP, SEXP ntypesSEXP, SEXP intensitiesSEXP, SEXP min_intensitiesSEXP, SEXP bdistSEXP, SEXP rSEXP, SEXP correctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< int >::type ntypes(ntypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type min_intensities(min_intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    rcpp_result_gen = Rcpp::wrap(c_iD_cross_2d_box(x, bbox, types, ntypes, intensities, min_intensities, bdist, r, correction));
    return rcpp_result_gen;
END_RCPP
}
// c_iD_cross_2d_box_from
List c_iD_cross_2d_box_from(NumericMatrix x, NumericMatrix bbox, NumericVector types, int ntypes, NumericVector intensities, NumericVector min_intensities, NumericVector bdist, NumericVector r, int correction, int from);
RcppExport SEXP _Kcross_c_iD_cross_2d_box_from(SEXP xSEXP, SEXP bboxSEXP, SEXP typesSEXP, SEXP ntypesSEXP, SEXP intensitiesSEXP, SEXP min_intensitiesSEXP, SEXP bdistSEXP, SEXP rSEXP, SEXP correctionSEXP, SEXP fromSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< int >::type ntypes(ntypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type min_intensities(min_intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    rcpp_result_gen = Rcpp::wrap(c_iD_cross_2d_box_from(x, bbox, types, ntypes, intensities, min_intensities, bdist, r, correction, from));
    return rcpp_result_gen;
END_RCPP
}
// c_iK_cross_2d_box
List c_iK_cross_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector types, int ntypes, NumericVector intensities, NumericVector r, int correction, bool verb);
RcppExport SEXP _Kcross_c_iK_cross_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP typesSEXP, SEXP ntypesSEXP, SEXP intensitiesSEXP, SEXP rSEXP, SEXP correctionSEXP, SEXP verbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< int >::type ntypes(ntypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    Rcpp::traits::input_parameter< bool >::type verb(verbSEXP);
    rcpp_result_gen = Rcpp::wrap(c_iK_cross_2d_box(x, bbox, types, ntypes, intensities, r, correction, verb));
    return rcpp_result_gen;
END_RCPP
}
// c_iK_2d_box
NumericVector c_iK_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector intensities, NumericVector r, int correction);
RcppExport SEXP _Kcross_c_iK_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP intensitiesSEXP, SEXP rSEXP, SEXP correctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    rcpp_result_gen = Rcpp::wrap(c_iK_2d_box(x, bbox, intensities, r, correction));
    return rcpp_result_gen;
END_RCPP
}
// c_ipcf_cross_2d_box
List c_ipcf_cross_2d_box(NumericMatrix x, NumericMatrix bbox, int ntypes, NumericVector types, NumericVector intensities, NumericVector r, double adjust, int correction, int verb);
RcppExport SEXP _Kcross_c_ipcf_cross_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP ntypesSEXP, SEXP typesSEXP, SEXP intensitiesSEXP, SEXP rSEXP, SEXP adjustSEXP, SEXP correctionSEXP, SEXP verbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< int >::type ntypes(ntypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type adjust(adjustSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    Rcpp::traits::input_parameter< int >::type verb(verbSEXP);
    rcpp_result_gen = Rcpp::wrap(c_ipcf_cross_2d_box(x, bbox, ntypes, types, intensities, r, adjust, correction, verb));
    return rcpp_result_gen;
END_RCPP
}
// c_ipcf_2d_box
NumericVector c_ipcf_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector intensities, double bw, NumericVector r, double adjust, int correction);
RcppExport SEXP _Kcross_c_ipcf_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP intensitiesSEXP, SEXP bwSEXP, SEXP rSEXP, SEXP adjustSEXP, SEXP correctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type adjust(adjustSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    rcpp_result_gen = Rcpp::wrap(c_ipcf_2d_box(x, bbox, intensities, bw, r, adjust, correction));
    return rcpp_result_gen;
END_RCPP
}
// c_ipcf_local_2d_box
NumericMatrix c_ipcf_local_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector intensities, double bw, NumericVector r, double adjust, int correction);
RcppExport SEXP _Kcross_c_ipcf_local_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP intensitiesSEXP, SEXP bwSEXP, SEXP rSEXP, SEXP adjustSEXP, SEXP correctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type adjust(adjustSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    rcpp_result_gen = Rcpp::wrap(c_ipcf_local_2d_box(x, bbox, intensities, bw, r, adjust, correction));
    return rcpp_result_gen;
END_RCPP
}
// c_ipcf_st_cross_2d_box
List c_ipcf_st_cross_2d_box(NumericMatrix x, NumericMatrix bbox, int ntypes, NumericVector types, NumericVector intensities, NumericVector r, NumericVector t, NumericVector sigmas, int correction);
RcppExport SEXP _Kcross_c_ipcf_st_cross_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP ntypesSEXP, SEXP typesSEXP, SEXP intensitiesSEXP, SEXP rSEXP, SEXP tSEXP, SEXP sigmasSEXP, SEXP correctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< int >::type ntypes(ntypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigmas(sigmasSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    rcpp_result_gen = Rcpp::wrap(c_ipcf_st_cross_2d_box(x, bbox, ntypes, types, intensities, r, t, sigmas, correction));
    return rcpp_result_gen;
END_RCPP
}
// c_pcf_biv_2d_box
NumericVector c_pcf_biv_2d_box(NumericMatrix x, int n1, NumericVector r, double bw, NumericMatrix bbox, int correction);
RcppExport SEXP _Kcross_c_pcf_biv_2d_box(SEXP xSEXP, SEXP n1SEXP, SEXP rSEXP, SEXP bwSEXP, SEXP bboxSEXP, SEXP correctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    rcpp_result_gen = Rcpp::wrap(c_pcf_biv_2d_box(x, n1, r, bw, bbox, correction));
    return rcpp_result_gen;
END_RCPP
}
// c_pcf_2d_box
NumericVector c_pcf_2d_box(NumericMatrix x, NumericVector r, double bw, NumericMatrix bbox, int correction, int kern);
RcppExport SEXP _Kcross_c_pcf_2d_box(SEXP xSEXP, SEXP rSEXP, SEXP bwSEXP, SEXP bboxSEXP, SEXP correctionSEXP, SEXP kernSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    Rcpp::traits::input_parameter< int >::type kern(kernSEXP);
    rcpp_result_gen = Rcpp::wrap(c_pcf_2d_box(x, r, bw, bbox, correction, kern));
    return rcpp_result_gen;
END_RCPP
}
// c_rho_cross_2d_box
List c_rho_cross_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector types, NumericVector intensities, NumericVector r, double adjust, int correction, bool kernel_correction, int verb);
RcppExport SEXP _Kcross_c_rho_cross_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP typesSEXP, SEXP intensitiesSEXP, SEXP rSEXP, SEXP adjustSEXP, SEXP correctionSEXP, SEXP kernel_correctionSEXP, SEXP verbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensities(intensitiesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type adjust(adjustSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    Rcpp::traits::input_parameter< bool >::type kernel_correction(kernel_correctionSEXP);
    Rcpp::traits::input_parameter< int >::type verb(verbSEXP);
    rcpp_result_gen = Rcpp::wrap(c_rho_cross_2d_box(x, bbox, types, intensities, r, adjust, correction, kernel_correction, verb));
    return rcpp_result_gen;
END_RCPP
}
// c_rho_2d_box
NumericVector c_rho_2d_box(NumericMatrix x, NumericMatrix bbox, NumericVector r, double bw, int correction, int kernel_correction, int kern);
RcppExport SEXP _Kcross_c_rho_2d_box(SEXP xSEXP, SEXP bboxSEXP, SEXP rSEXP, SEXP bwSEXP, SEXP correctionSEXP, SEXP kernel_correctionSEXP, SEXP kernSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< int >::type correction(correctionSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_correction(kernel_correctionSEXP);
    Rcpp::traits::input_parameter< int >::type kern(kernSEXP);
    rcpp_result_gen = Rcpp::wrap(c_rho_2d_box(x, bbox, r, bw, correction, kernel_correction, kern));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Kcross_c_D_cross_2d_box", (DL_FUNC) &_Kcross_c_D_cross_2d_box, 5},
    {"_Kcross_c_K_cross_2d_box", (DL_FUNC) &_Kcross_c_K_cross_2d_box, 6},
    {"_Kcross_c_K_2d_box", (DL_FUNC) &_Kcross_c_K_2d_box, 4},
    {"_Kcross_c_K_cross_2d_box_just_one_from", (DL_FUNC) &_Kcross_c_K_cross_2d_box_just_one_from, 7},
    {"_Kcross_c_K_cross_partial_box", (DL_FUNC) &_Kcross_c_K_cross_partial_box, 7},
    {"_Kcross_c_K_partial_box", (DL_FUNC) &_Kcross_c_K_partial_box, 3},
    {"_Kcross_c_bbox_disc_intersection", (DL_FUNC) &_Kcross_c_bbox_disc_intersection, 3},
    {"_Kcross_c_guan_doublesum_2d_box", (DL_FUNC) &_Kcross_c_guan_doublesum_2d_box, 3},
    {"_Kcross_c_iD_cross_2d_box", (DL_FUNC) &_Kcross_c_iD_cross_2d_box, 9},
    {"_Kcross_c_iD_cross_2d_box_from", (DL_FUNC) &_Kcross_c_iD_cross_2d_box_from, 10},
    {"_Kcross_c_iK_cross_2d_box", (DL_FUNC) &_Kcross_c_iK_cross_2d_box, 8},
    {"_Kcross_c_iK_2d_box", (DL_FUNC) &_Kcross_c_iK_2d_box, 5},
    {"_Kcross_c_ipcf_cross_2d_box", (DL_FUNC) &_Kcross_c_ipcf_cross_2d_box, 9},
    {"_Kcross_c_ipcf_2d_box", (DL_FUNC) &_Kcross_c_ipcf_2d_box, 7},
    {"_Kcross_c_ipcf_local_2d_box", (DL_FUNC) &_Kcross_c_ipcf_local_2d_box, 7},
    {"_Kcross_c_ipcf_st_cross_2d_box", (DL_FUNC) &_Kcross_c_ipcf_st_cross_2d_box, 9},
    {"_Kcross_c_pcf_biv_2d_box", (DL_FUNC) &_Kcross_c_pcf_biv_2d_box, 6},
    {"_Kcross_c_pcf_2d_box", (DL_FUNC) &_Kcross_c_pcf_2d_box, 6},
    {"_Kcross_c_rho_cross_2d_box", (DL_FUNC) &_Kcross_c_rho_cross_2d_box, 9},
    {"_Kcross_c_rho_2d_box", (DL_FUNC) &_Kcross_c_rho_2d_box, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_Kcross(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
