# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_D_cross_2d_box <- function(x, bbox, types, intensities, r) {
    .Call('_Kcross_c_D_cross_2d_box', PACKAGE = 'Kcross', x, bbox, types, intensities, r)
}

c_K_cross_2d_box <- function(x, bbox, types, ntypes, r, correction) {
    .Call('_Kcross_c_K_cross_2d_box', PACKAGE = 'Kcross', x, bbox, types, ntypes, r, correction)
}

c_K_2d_box <- function(x, bbox, r, correction) {
    .Call('_Kcross_c_K_2d_box', PACKAGE = 'Kcross', x, bbox, r, correction)
}

c_K_cross_2d_box_just_one_from <- function(x, bbox, types, from, ntypes, r, correction) {
    .Call('_Kcross_c_K_cross_2d_box_just_one_from', PACKAGE = 'Kcross', x, bbox, types, from, ntypes, r, correction)
}

c_K_cross_partial_box <- function(x, types, ntypes, counts, intensities, bbox, r) {
    .Call('_Kcross_c_K_cross_partial_box', PACKAGE = 'Kcross', x, types, ntypes, counts, intensities, bbox, r)
}

c_K_partial_box <- function(x, bbox, r) {
    .Call('_Kcross_c_K_partial_box', PACKAGE = 'Kcross', x, bbox, r)
}

c_bbox_disc_intersection <- function(x, bbox, r) {
    .Call('_Kcross_c_bbox_disc_intersection', PACKAGE = 'Kcross', x, bbox, r)
}

c_guan_doublesum_2d_box <- function(x, bbox, bw) {
    .Call('_Kcross_c_guan_doublesum_2d_box', PACKAGE = 'Kcross', x, bbox, bw)
}

c_iD_cross_2d_box <- function(x, bbox, types, ntypes, intensities, min_intensities, bdist, r, correction) {
    .Call('_Kcross_c_iD_cross_2d_box', PACKAGE = 'Kcross', x, bbox, types, ntypes, intensities, min_intensities, bdist, r, correction)
}

c_iD_cross_2d_box_from <- function(x, bbox, types, ntypes, intensities, min_intensities, bdist, r, correction, from) {
    .Call('_Kcross_c_iD_cross_2d_box_from', PACKAGE = 'Kcross', x, bbox, types, ntypes, intensities, min_intensities, bdist, r, correction, from)
}

c_iK_cross_2d_box <- function(x, bbox, types, ntypes, intensities, r, correction, verb) {
    .Call('_Kcross_c_iK_cross_2d_box', PACKAGE = 'Kcross', x, bbox, types, ntypes, intensities, r, correction, verb)
}

c_iK_2d_box <- function(x, bbox, intensities, r, correction) {
    .Call('_Kcross_c_iK_2d_box', PACKAGE = 'Kcross', x, bbox, intensities, r, correction)
}

c_ipcf_cross_2d_box <- function(x, bbox, ntypes, types, intensities, r, adjust = 1, correction = 1L, verb = 0L) {
    .Call('_Kcross_c_ipcf_cross_2d_box', PACKAGE = 'Kcross', x, bbox, ntypes, types, intensities, r, adjust, correction, verb)
}

c_ipcf_2d_box <- function(x, bbox, intensities, bw, r, adjust, correction) {
    .Call('_Kcross_c_ipcf_2d_box', PACKAGE = 'Kcross', x, bbox, intensities, bw, r, adjust, correction)
}

c_ipcf_local_2d_box <- function(x, bbox, intensities, bw, r, adjust, correction) {
    .Call('_Kcross_c_ipcf_local_2d_box', PACKAGE = 'Kcross', x, bbox, intensities, bw, r, adjust, correction)
}

c_ipcf_st_cross_2d_box <- function(x, bbox, ntypes, types, intensities, r, t, sigmas, correction) {
    .Call('_Kcross_c_ipcf_st_cross_2d_box', PACKAGE = 'Kcross', x, bbox, ntypes, types, intensities, r, t, sigmas, correction)
}

c_pcf_biv_2d_box <- function(x, n1, r, bw, bbox, correction) {
    .Call('_Kcross_c_pcf_biv_2d_box', PACKAGE = 'Kcross', x, n1, r, bw, bbox, correction)
}

c_pcf_2d_box <- function(x, r, bw, bbox, correction, kern = 1L) {
    .Call('_Kcross_c_pcf_2d_box', PACKAGE = 'Kcross', x, r, bw, bbox, correction, kern)
}

c_rho_cross_2d_box <- function(x, bbox, types, intensities, r, adjust, correction, kernel_correction, verb = 0L) {
    .Call('_Kcross_c_rho_cross_2d_box', PACKAGE = 'Kcross', x, bbox, types, intensities, r, adjust, correction, kernel_correction, verb)
}

c_rho_2d_box <- function(x, bbox, r, bw, correction, kernel_correction, kern = 1L) {
    .Call('_Kcross_c_rho_2d_box', PACKAGE = 'Kcross', x, bbox, r, bw, correction, kernel_correction, kern)
}

