# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_bbox_disc_intersection <- function(x, bbox, r) {
    .Call('Kcross_c_bbox_disc_intersection', PACKAGE = 'Kcross', x, bbox, r)
}

c_D_cross_2d_box <- function(x, bbox, types, intensities, r) {
    .Call('Kcross_c_D_cross_2d_box', PACKAGE = 'Kcross', x, bbox, types, intensities, r)
}

c_guan_doublesum_2d_box <- function(x, bbox, bw) {
    .Call('Kcross_c_guan_doublesum_2d_box', PACKAGE = 'Kcross', x, bbox, bw)
}

c_iK_cross_2d_box <- function(x, bbox, types, ntypes, intensities, r, correction) {
    .Call('Kcross_c_iK_cross_2d_box', PACKAGE = 'Kcross', x, bbox, types, ntypes, intensities, r, correction)
}

c_iK_2d_box <- function(x, bbox, intensities, r, correction) {
    .Call('Kcross_c_iK_2d_box', PACKAGE = 'Kcross', x, bbox, intensities, r, correction)
}

c_ipcf_cross_2d_box <- function(x, bbox, ntypes, types, intensities, r, adjust, correction) {
    .Call('Kcross_c_ipcf_cross_2d_box', PACKAGE = 'Kcross', x, bbox, ntypes, types, intensities, r, adjust, correction)
}

c_ipcf_2d_box <- function(x, bbox, intensities, bw, r, adjust, correction) {
    .Call('Kcross_c_ipcf_2d_box', PACKAGE = 'Kcross', x, bbox, intensities, bw, r, adjust, correction)
}

c_K_cross_2d_box <- function(x, bbox, types, ntypes, r, correction) {
    .Call('Kcross_c_K_cross_2d_box', PACKAGE = 'Kcross', x, bbox, types, ntypes, r, correction)
}

c_K_2d_box <- function(x, bbox, r, correction) {
    .Call('Kcross_c_K_2d_box', PACKAGE = 'Kcross', x, bbox, r, correction)
}

c_K_cross_2d_box_just_one_from <- function(x, bbox, types, from, ntypes, r, correction) {
    .Call('Kcross_c_K_cross_2d_box_just_one_from', PACKAGE = 'Kcross', x, bbox, types, from, ntypes, r, correction)
}

c_K_cross_partial_box <- function(x, types, ntypes, counts, intensities, bbox, r) {
    .Call('Kcross_c_K_cross_partial_box', PACKAGE = 'Kcross', x, types, ntypes, counts, intensities, bbox, r)
}

c_K_partial_box <- function(x, bbox, r) {
    .Call('Kcross_c_K_partial_box', PACKAGE = 'Kcross', x, bbox, r)
}

c_rho_cross_2d_box <- function(x, bbox, types, intensities, r, adjust, correction) {
    .Call('Kcross_c_rho_cross_2d_box', PACKAGE = 'Kcross', x, bbox, types, intensities, r, adjust, correction)
}

c_rho_2d_box <- function(x, bbox, intensity, r, bw, correction, kern = 1L) {
    .Call('Kcross_c_rho_2d_box', PACKAGE = 'Kcross', x, bbox, intensity, r, bw, correction, kern)
}

c_pcf_biv_2d_box <- function(x, n1, r, bw, bbox, correction) {
    .Call('Kcross_c_pcf_biv_2d_box', PACKAGE = 'Kcross', x, n1, r, bw, bbox, correction)
}

c_pcf_2d_box <- function(x, r, bw, bbox, correction, kern = 1L) {
    .Call('Kcross_c_pcf_2d_box', PACKAGE = 'Kcross', x, r, bw, bbox, correction, kern)
}

